name: Documentation Script CI

on:
  push:
    branches: [ "feature/develop/task4" ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  pull_request:
    branches: [ "feature/develop/task4" ]
  workflow_dispatch:

jobs:
  documentation-generation:
    name: Documentation Generation
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Doxygen Script
        shell: pwsh
        run: |
          ./ci/windows/docs-script.ps1

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: csad2425ki405volodymyrhnidets03-app-documentation
          path: ./ci-build/docs/*
