name: CI for ESP32

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  arduino:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Arduino CLI
        uses: arduino/setup-arduino-cli@v1
        with:
          version: '0.19.2'

      - name: Install ESP32 platform
        run: arduino-cli core install esp32:esp32

      - name: Build ESP32 Project
        run: |
          arduino-cli compile --fqbn esp32:esp32:esp32dev server/hw_uart_transmit/hw_uart_transmit.ino

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: esp32-build
          path: server/hw_uart_transmit/build/*
